language: bash
sudo: required

services:
 - docker

jobs:
 include:
  - stage: Build
    script: docker build -t cdemi/hello-world .
  - stage: Test
    script: \[ "$(docker run --rm cdemi/hello-world)" == "Hello World!" \]