language: bash
sudo: required
os:
 - linux
 - windows
services:
 - docker

script:
 - docker build -t cdemi/hello-world:$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH .
 - \[ "$(docker run --rm cdemi/hello-world:$TRAVIS_BUILD_NUMBER-$TRAVIS_BRANCH)" == "Hello World!" \]