image:
- Ubuntu
- Visual Studio 2017

services:
- docker

build_script:
- ps: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- ps: docker build -t cdemi/hello-world .
- ps: docker run --rm cdemi/hello-world