image:
- Ubuntu
- Visual Studio 2017

services:
- docker

build_script:
- sh: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- sh: docker build -t cdemi/hello-world .
- sh: docker run --rm cdemi/hello-world