image:
- Visual Studio 2017
- Ubuntu

services:
- docker

build_script:
- pwsh: Get-Variable | Out-String
- pwsh: |
    $ENV:DOCKER_TAG="$ENV:APPVEYOR_BUILD_VERSION"
    if ($isLinux) {
      Write-Host "Working on Linux"
      $ENV:DOCKER_TAG+="-linux"
    } else {
      Write-Host "Working on Windows"
      $ENV:DOCKER_TAG+="-windows"
    }
- pwsh: 'Write-Host "Let see: $test"'
- pwsh: 'Write-Host "Building Tag: $ENV:DOCKER_TAG"'
- pwsh: docker login -u "$ENV:DOCKER_USERNAME" -p "$ENV:DOCKER_PASSWORD"
- pwsh: docker build -t cdemi/hello-world:$ENV:DOCKER_TAG .
- pwsh: docker run --rm cdemi/hello-world:$ENV:DOCKER_TAG
- pwsh: docker push cdemi/hello-world:$ENV:DOCKER_TAG